export const LeadData = [
  {
    id: 1,
    name: "Aharon Lisett",
    email: "alisett0@symantec.com",
    title: "Computer Systems Analyst IV",
    department: "Services",
    status: "Active",
    role: "Construction Worker",
  },
  {
    id: 2,
    name: "Sheppard Jobke",
    email: "sjobke1@rediff.com",
    title: "Environmental Specialist",
    department: "Research and Development",
    status: "Active",
    role: "Estimator",
  },
  {
    id: 3,
    name: "Alan Witton",
    email: "awitton2@tripadvisor.com",
    title: "Senior Developer",
    department: "Marketing",
    status: "Pending",
    role: "Architect",
  },
  {
    id: 4,
    name: "Paolo Gogie",
    email: "pgogie3@time.com",
    title: "Project Manager",
    department: "Support",
    status: "Active",
    role: "Surveyor",
  },
  {
    id: 5,
    name: "Nolan Babar",
    email: "nbabar4@mashable.com",
    title: "Editor",
    department: "Human Resources",
    status: "Rejected",
    role: "Construction Foreman",
  },
  {
    id: 6,
    name: "Stanford Delph",
    email: "sdelph5@icio.us",
    title: "Systems Administrator IV",
    department: "Support",
    status: "Active",
    role: "Subcontractor",
  },
  {
    id: 7,
    name: "Britney Roze",
    email: "broze6@usda.gov",
    title: "VP Marketing",
    department: "Human Resources",
    status: "Pending",
    role: "Surveyor",
  },
  {
    id: 8,
    name: "Kyle O'Halligan",
    email: "kohalligan7@arizona.edu",
    title: "Business Systems Development Analyst",
    department: "Accounting",
    status: "Active",
    role: "Construction Expeditor",
  },
  {
    id: 9,
    name: "Cyb Manuele",
    email: "cmanuele8@linkedin.com",
    title: "VP Quality Control",
    department: "Research and Development",
    status: "Completed",
    role: "Electrician",
  },
  {
    id: 10,
    name: "Harper Saph",
    email: "hsaph9@sourceforge.net",
    title: "Accountant IV",
    department: "Support",
    status: "Active",
    role: "Supervisor",
  },
  {
    id: 11,
    name: "Kirbee Rackham",
    email: "krackhama@arizona.edu",
    title: "Assistant Media Planner",
    department: "Legal",
    status: "Active",
    role: "Supervisor",
  },
  {
    id: 12,
    name: "Martguerita Mackley",
    email: "mmackleyb@bluehost.com",
    title: "Operator",
    department: "Legal",
    status: "Active",
    role: "Construction Expeditor",
  },
  {
    id: 13,
    name: "Quentin Suermeiers",
    email: "qsuermeiersc@ebay.com",
    title: "Nurse Practicioner",
    department: "Business Development",
    status: "Pending",
    role: "Estimator",
  },
  {
    id: 14,
    name: "Brianna Czadla",
    email: "bczadlad@tiny.cc",
    title: "Assistant Professor",
    department: "Business Development",
    status: "Active",
    role: "Construction Manager",
  },
  {
    id: 15,
    name: "Pansie Knight",
    email: "pknighte@w3.org",
    title: "Teacher",
    department: "Product Management",
    status: "Rejected",
    role: "Surveyor",
  },
  {
    id: 16,
    name: "Gertrude Gabrieli",
    email: "ggabrielif@discovery.com",
    title: "Financial Advisor",
    department: "Sales",
    status: "Active",
    role: "Surveyor",
  },
  {
    id: 17,
    name: "Frannie Bengochea",
    email: "fbengocheag@fc2.com",
    title: "Physical Therapy Assistant",
    department: "Training",
    status: "Active",
    role: "Engineer",
  },
  {
    id: 18,
    name: "Noel Sollom",
    email: "nsollomh@ca.gov",
    title: "Environmental Specialist",
    department: "Legal",
    status: "Pending",
    role: "Construction Expeditor",
  },
  {
    id: 19,
    name: "Sybilla Milne",
    email: "smilnei@flavors.me",
    title: "Senior Editor",
    department: "Research and Development",
    status: "Active",
    role: "Construction Manager",
  },
  {
    id: 20,
    name: "Aron Freckleton",
    email: "afreckletonj@globo.com",
    title: "Financial Advisor",
    department: "Sales",
    status: "Completed",
    role: "Project Manager",
  }
]

